sm8250: Techpack: Camera-Xiaomi & camera-xiaomi-cas: Fix missing type specifier
Fixing error:
../../../../../../kernel/xiaomi/sm8250/techpack/camera-xiaomi/drivers/cam_req_mgr/cam_req_mgr_util.c:21:8: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
static hdl_count = 0;
~~~~~~ ^
int
1 error generated.